# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'gamedemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gamedemo
  pod 'ZYGameKit-swift', '~> 1.1.8'
  pod 'ZYOtherLoginKit', '~> 1.0.2'
  
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  
end
